create table saved_tweets (
  id bigint generated by default as identity primary key,
  content text not null,
  source_text text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add a policy to allow all operations for now (you can restrict this later)
alter table saved_tweets enable row level security;

create policy "Allow all operations for all users" on saved_tweets
  for all
  using (true)
  with check (true); 